apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
  namespace: audit-zone
spec:
  containers:
    - name: busybox
      image: busybox:latest
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: host-volume
          mountPath: /host
  volumes:
    - name: host-volume
      hostPath:
        path: /etc
        type: Directory