apiVersion: v1
kind: Pod
metadata:
  name: root-user-pod
  namespace: audit-zone
spec:
  containers:
    - name: alpine
      image: alpine:latest
      command: ["sh", "-c", "sleep 3600"]
      securityContext:
        runAsUser: 0
        runAsNonRoot: false