@startmindmap
<style>
node {
    Padding 12
    Margin 3
    MaximumWidth 200
}

</style>

* Безопасность данных
**[#Lavender] Публичные данные
***[#Lavender] Информация о ЖК (описания, фото, Онлайн-витрина, Онлайн-тур)
****[#Orange]:Риск: Искажение данных
Оценка: Значительный
Обоснование: Неверные данные снижают доверие клиентов;
***[#Lavender] Отчёты по ремонту (публичные)
****[#Moccasin]:Риск: Обесценивание данных
Оценка: Незначительный
Обоснование: Устаревшая информация дезориентирует;
**[#Thistle] Внутренние данные
***[#Thistle] Техдокументация систем
****[#Orange]:Риск: Некачественные данные
Оценка: Значительный
Обоснование: Ошибки ведут к сбоям в разработке;
***[#Thistle] Логи взаимодействия команд
****[#Orange]:Риск: Утечка данных
Оценка: Значительный
Обоснование: Раскрытие процессов конкурентам;



**[#Plum] Конфиденциальные данные
***[#Plum] Персональные данные клиентов (Ф.И.О., телефон, email)
****[#Tomato]:Риск: Утечка данных
Оценка: Критический
Обоснование: Нарушение закона, штрафы, репутационный ущерб;
***[#Plum] Данные о бронированиях и сделках
****[#Tomato]:Риск: Искажение данных
Оценка: Критический
Обоснование: Ошибки в сделках ведут к финансовым потерям;
***[#Plum] Данные собственников (ЖКХ, доступ к Умному дому)
****[#Tomato]:Риск: Потеря данных
Оценка: Критический
Обоснование: Сбой резервного копирования;
**[#Violet] Секретные данные
***[#Violet] Ключи интеграции с госорганами
****[#Tomato]:Риск: Утечка данных
Оценка: Критический
Обоснование: Компрометация приводит к блокировке услуг;
***[#Violet] Партнёрские API-ключи
****[#Tomato]:Риск: Утечка данных
Оценка: Критический
Обоснование: Несанкционированный доступ к данным партнёров;
***[#Violet] Исходный код систем
****[#Tomato]:Риск: Обесценивание данных
Оценка: Критический
Обоснование: Раскрытие уязвимостей;
@endmindmap