apiVersion: v1
kind: Pod
metadata:
  name: secure-root-user-pod
  namespace: audit-zone
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    fsGroup: 2000
  containers:
    - name: alpine
      image: alpine:latest
      command: ["sh", "-c", "sleep 3600"]
      securityContext:
        runAsUser: 1000
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false